%% config parameters 

%% from lua file, auto generated by TI tool 
Cfg.numADCSample = 512; 
Cfg.numChirpsPerLoop = 16;
Cfg.adcSampleRate = 10e6; %Hz/s 
Cfg.chirpIdleTime = 6.0e-06; %s 
Cfg.adcStartTimeConst = 4.0e-06; %s 
Cfg.chirpRampEndTime = 108.4e-06; %s 
Cfg.NumDevices = 4; 
Cfg.numLoops = 16; 
Cfg.numTxAnt = 12; 
Cfg.numRxAnt = 16;

Cfg.startFreqConst = 76e9; %Hz
Cfg.chirpSlope = 14.677048e12; %Hz/s

%% constants
Cfg.speedOfLight        = 3e8;

%% derived parameters
Cfg.numChirpsPerFrame   = Cfg.numLoops* Cfg.numChirpsPerLoop;
Cfg.DopplerFFTSize      = Cfg.numChirpsPerFrame;
Cfg.chirpRampTime       = Cfg.numADCSample/Cfg.adcSampleRate;
Cfg.chirpBandwidth      = Cfg.chirpSlope * Cfg.chirpRampTime; % Hz
Cfg.chirpInterval       = Cfg.chirpRampEndTime + Cfg.chirpIdleTime;
Cfg.carrierFrequency    = Cfg.startFreqConst +  (Cfg.adcStartTimeConst + Cfg.chirpRampTime/2)*Cfg.chirpSlope; % Hz center frequency
Cfg.lambda              = Cfg.speedOfLight/Cfg.carrierFrequency;
Cfg.maximumVelocity     = Cfg.lambda / (Cfg.chirpInterval*2) ; % m/s
Cfg.maxRange            = Cfg.speedOfLight*Cfg.adcSampleRate*Cfg.chirpRampTime/(2*Cfg.chirpBandwidth);
Cfg.numSamplePerChirp   = round(Cfg.chirpRampTime*Cfg.adcSampleRate);
Cfg.rangeFFTSize        = 2^(ceil(log2(Cfg.numSamplePerChirp)));
Cfg.numVirtualRxAnt     = Cfg.numTxAnt * Cfg.numRxAnt ;
Cfg.rangeResolution     = Cfg.speedOfLight/2/Cfg.chirpBandwidth;
Cfg.rangeBinSize        = Cfg.rangeResolution*Cfg.numSamplePerChirp/Cfg.rangeFFTSize;
Cfg.velocityResolution  = Cfg.lambda / (2*Cfg.numChirpsPerFrame * Cfg.chirpInterval);
Cfg.velocityBinSize     = Cfg.velocityResolution*Cfg.numChirpsPerFrame/Cfg.DopplerFFTSize;

%% Processing %%
Cfg.NumSamp = Cfg.numADCSample; 
Cfg.NumChirps = Cfg.numChirpsPerFrame; 
Cfg.NumDoppConvert = Cfg.DopplerFFTSize/Cfg.numChirpsPerLoop;
Cfg.numRangeBin    = Cfg.NumSamp; 
